apiVersion: v1
kind: Service
metadata:
  name: wil42-playground
spec:
  type: NodePort
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 30042
  selector:
    app: wil42-playground-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil42-playground-deployment
  labels:
    app: wil42-playground-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wil42-playground-app
  template:
    metadata:
      labels:
        app: wil42-playground-app
    spec:
      containers:
      - image: wil42/playground:v1
        name: wil42-playground
        ports:
        - containerPort: 8888
